- doc.py:138 (parse_syntax) # Синтаксический анализ
- infer.py:81 (__call__) # Основной вызов модели синтаксического анализа
- model.py:277 (__call__) # Получение предсказаний
- model.py:397 (decode) # Построение графа зависимостей
- navec:60:load # Загрузка эмбеддингов
